# Generated by Django 3.1.4 on 2021-01-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(max_length=40)),
                ('pid', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('c_name', models.CharField(max_length=40)),
                ('image', models.CharField(max_length=40)),
                ('img', models.CharField(max_length=40)),
                ('picture', models.CharField(max_length=40)),
                ('pic', models.CharField(max_length=40)),
                ('pica', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=1000)),
                ('engine', models.CharField(max_length=40)),
                ('displacement', models.CharField(max_length=40)),
                ('power', models.CharField(max_length=40)),
                ('drivetrain', models.CharField(max_length=40)),
                ('fuel_tank_capacity', models.CharField(max_length=40)),
                ('airbags', models.CharField(max_length=40)),
                ('dt', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=40)),
                ('qty', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('c_name', models.CharField(max_length=40)),
                ('image', models.CharField(max_length=40)),
                ('img', models.CharField(max_length=40)),
                ('picture', models.CharField(max_length=40)),
                ('pic', models.CharField(max_length=40)),
                ('pica', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=40)),
                ('engine', models.CharField(max_length=40)),
                ('displacement', models.CharField(max_length=40)),
                ('power', models.CharField(max_length=40)),
                ('drivetrain', models.CharField(max_length=40)),
                ('fuel_tank_capacity', models.CharField(max_length=40)),
                ('airbags', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Show_cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('c_name', models.CharField(max_length=40)),
                ('image', models.CharField(max_length=40)),
                ('img', models.CharField(max_length=40)),
                ('picture', models.CharField(max_length=40)),
                ('pic', models.CharField(max_length=40)),
                ('pica', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=1000)),
                ('engine', models.CharField(max_length=40)),
                ('displacement', models.CharField(max_length=40)),
                ('power', models.CharField(max_length=40)),
                ('drivetrain', models.CharField(max_length=40)),
                ('fuel_tank_capacity', models.CharField(max_length=40)),
                ('airbags', models.CharField(max_length=40)),
                ('dt', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('mobile_number', models.CharField(max_length=40)),
                ('email_id', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
            ],
        ),
    ]
