# Generated by Django 3.1.4 on 2021-02-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=40)),
                ('user', models.CharField(max_length=40)),
                ('product', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('dt', models.CharField(max_length=40)),
            ],
        ),
    ]
